version: '3.1'
services:
    web:
        build: .
        ports:
            - 80:80
        expose:
            - 80
        volumes:
            - ./htdocs:/var/www/html/
    
    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - 8080:80
        expose:
            - 8080
        environment:
            PMA_HOSTS: host.docker.internal
            PMA_PORTS: 3306
            MYSQL_ROOT_PASSWORD: 1234 

volumes:
   phypmyadmin: 